version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    env_file:
      - '.env'
    stdin_open: true
    tty: true
  db:
    image: postgis/postgis:14-3.3
    env_file:
      - '.env'
